import { Item, YouTubeStats } from "./types";

// Sample data so the dashboard is fully alive before any key is added.
// Once Supabase + integrations are configured, real data replaces all of this.

const now = Date.now();
const hours = (h: number) => new Date(now + h * 3600_000).toISOString();
const daysAgo = (d: number) => new Date(now - d * 86400_000).toISOString();

export const sampleItems: Item[] = [
  {
    id: "s1",
    created_at: daysAgo(0),
    type: "task",
    title: "Follow up with supplier about delayed festival order",
    details: "They promised an update by EOD. If no reply, call directly.",
    priority: "high",
    category: "business",
    status: "open",
    due_at: hours(4),
    source: "telegram",
    raw_transcript: "remind me to follow up with the supplier about the delayed order",
  },
  {
    id: "s2",
    created_at: daysAgo(0),
    type: "idea",
    title: "Bundle the two products for the festival sale",
    details: "Could lift average order value. Test a limited-time combo price.",
    priority: "medium",
    category: "business",
    status: "open",
    due_at: null,
    source: "telegram",
    raw_transcript: "we should bundle the two products for the festival sale",
  },
  {
    id: "s3",
    created_at: daysAgo(1),
    type: "task",
    title: "Record next YouTube video: '3 AI tools I use daily'",
    details: "Script is half done. Aim to shoot before the weekend.",
    priority: "high",
    category: "business",
    status: "open",
    due_at: hours(30),
    source: "manual",
    raw_transcript: null,
  },
  {
    id: "s4",
    created_at: daysAgo(1),
    type: "reminder",
    title: "Call Mom on her birthday",
    details: null,
    priority: "high",
    category: "personal",
    status: "open",
    due_at: hours(20),
    source: "telegram",
    raw_transcript: "don't let me forget mom's birthday call",
  },
  {
    id: "s5",
    created_at: daysAgo(2),
    type: "task",
    title: "Review Q3 ad spend and pause underperforming campaigns",
    details: "Meta CPMs creeping up. Reallocate to the two winners.",
    priority: "medium",
    category: "business",
    status: "open",
    due_at: hours(52),
    source: "manual",
    raw_transcript: null,
  },
  {
    id: "s6",
    created_at: daysAgo(3),
    type: "idea",
    title: "Weekly 'founder notes' newsletter to repurpose voice notes",
    details: "Turn the best captured thoughts into a Friday email.",
    priority: "low",
    category: "business",
    status: "open",
    due_at: null,
    source: "telegram",
    raw_transcript: "idea - a weekly newsletter from my notes",
  },
  {
    id: "s7",
    created_at: daysAgo(2),
    type: "task",
    title: "Book dentist appointment",
    details: null,
    priority: "low",
    category: "personal",
    status: "open",
    due_at: null,
    source: "telegram",
    raw_transcript: "book a dentist appointment sometime",
  },
  {
    id: "s8",
    created_at: daysAgo(4),
    type: "task",
    title: "Ship pricing page update",
    details: "Added the annual plan. Done and live.",
    priority: "medium",
    category: "business",
    status: "done",
    due_at: daysAgo(1),
    source: "manual",
    raw_transcript: null,
  },
  {
    id: "s9",
    created_at: daysAgo(5),
    type: "reminder",
    title: "Renew domain before it expires",
    details: "Auto-renew was off. Fixed.",
    priority: "high",
    category: "business",
    status: "done",
    due_at: daysAgo(2),
    source: "telegram",
    raw_transcript: null,
  },
];

export const sampleYouTube: YouTubeStats = {
  channelTitle: "The Solo Entrepreneur",
  subscribers: 24800,
  totalViews: 1_920_000,
  videoCount: 87,
  updatedAt: new Date().toISOString(),
  recent: [
    {
      id: "y1",
      title: "I automated my whole business with AI (here's how)",
      views: 48200,
      publishedAt: daysAgo(4),
      thumbnail: null,
    },
    {
      id: "y2",
      title: "5 AI tools every founder should steal",
      views: 31500,
      publishedAt: daysAgo(11),
      thumbnail: null,
    },
    {
      id: "y3",
      title: "Building a personal assistant that runs my life",
      views: 12750,
      publishedAt: daysAgo(18),
      thumbnail: null,
    },
    {
      id: "y4",
      title: "Why I fired my to-do list",
      views: 8900,
      publishedAt: daysAgo(25),
      thumbnail: null,
    },
  ],
};
